name: ACH Benchmarks
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    uses: moov-io/benchmarks/.github/workflows/bench.yml@master
    secrets: inherit
    needs: manifest
    with:
      name: ach
      command: |
        go test . -bench BenchmarkBuildFile -benchmem > output.txt
        go test . -bench Read -benchmem >> output.txt
        go test . -bench Write -benchmem >> output.txt
        go test . -bench AlphaField -benchmem >> output.txt
        go test . -bench NumericField -benchmem >> output.txt
        go test . -bench ParseNumField -benchmem >> output.txt
        go test . -bench ParseStringField -benchmem >> output.txt
        go test . -bench BenchmarkMergeFiles -benchmem >> output.txt
        go test . -bench BenchmarkCalculateCheckDigit -benchmem >> output.txt
