name: Run Benchmarks
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      org:
        required: false
        type: string
        default: "moov-io"
      branch:
        required: false
        type: string
        default: "master"
      setup:
        required: false
        type: string
      command:
        required: true
        type: string
      setup_ssh_key:
        required: false
        type: boolean
        default: false
      output_dir:
        required: false
        type: string
    secrets:
      ssh_key:
        required: false

permissions:
  deployments: write
  contents: write

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        if: ${{ inputs.setup_ssh_key }}
        with:
          ssh-private-key: ${{ secrets.ssh_key }}

      - name: Configure git to use SSH key
        if: ${{ inputs.setup_ssh_key }}
        run: 'git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"'

      - uses: actions/checkout@v4
        with:
          repository: 'moov-io/benchmarks'

      - uses: actions/checkout@v4
        with:
          repository: "${{inputs.org}}/${{inputs.name}}"
          ref: "${{inputs.branch}}"
          path: "./${{inputs.name}}/"

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Pre-benchmark Setup
        run: |
          ${{inputs.setup}}

      - name: Running Benchmarks
        id: run-benchmarks
        run: |
          cd ./${{inputs.name}}/
          echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          ${{inputs.command}}

      - name: Show Benchmark Results
        run: |
          cat ./${{inputs.name}}/output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "${{inputs.org}}/${{inputs.name}} Benchmarks"
          tool: 'go'
          output-file-path: "./${{inputs.name}}/output.txt"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-fetch-gh-pages: true
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '120%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@adamdecaf'
          # Use the ref of the project being benchmarked, not of moov-io/benchmarks
          ref: '${{ steps.run-benchmarks.outputs.hash }}'
          # Update files on master branch
          gh-pages-branch: master
          benchmark-data-dir-path: "docs/bench/${{ inputs.output_dir != '' && inputs.output_dir || inputs.name }}/"

      - name: Logs
        if: ${{ failure() }}
        run: |
          cat ./${{inputs.name}}/output.txt
