name: watchman Benchmarks
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

permissions:
  deployments: write
  contents: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      # "The workflow must contain at least one job with no dependencies."
      - run: date

  benchmark:
    uses: moov-io/benchmarks/.github/workflows/bench.yml@master
    secrets: inherit
    with:
      name: watchman
      setup: |
          sudo apt-get install -y libgl1-mesa-dev and xorg-dev
          make install
      command: |
        go test ./internal/search/... -short -bench Benchmark_Search -run Benchmark_Search -benchmem > output.txt
        go test ./internal/stringscore/... -short -bench BenchmarkJaroWinkler -run BenchmarkJaroWinkler -benchmem >> output.txt
        go test ./internal/postalpool/... -short -bench BenchmarkPostalPool -run BenchmarkPostalPool -benchmem >> output.txt
        go test -tags libpostal ./pkg/address/... -bench=Bench -run Bench -benchmem >> output.txt
