name: watchman Benchmarks
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

permissions:
  deployments: write
  contents: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      # "The workflow must contain at least one job with no dependencies."
      - run: date

  benchmark:
    uses: moov-io/benchmarks/.github/workflows/bench.yml@master
    secrets: inherit
    with:
      name: watchman
      command: |
        go test ./... -bench BenchmarkSearchHandler -benchmem > output.txt
        go test ./... -bench BenchmarkJaroWinkler -benchmem >> output.txt
